### PR TITLE
Use rot.js from WebJars

### LINKED ISSUE #1: Create webjar for rot.js
For proper dependency management we should definitely create and use a rot.js webjar artifact.

### PR DESCRIPTION
**Pull request by ForNeVeR**
I've successfully managed to publish rot.js to WebJars and we can use the published artifact. Also I've updated sbt, scala and Scala.js versions (because we need all that stuff to use WebJars).

Closes #1.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
cc @Akon32

**Comment by ForNeVeR** [comment]
Hm, @Akon32 seems to be unavailable for now. Let's try @rexim then!

**Comment by rexim** [comment]
Well, I don't see any problems with the changes. I approve them.

**Comment by ForNeVeR** [comment]
Thank you for review!

**Pull request merged**
