### PR TITLE
Add Travis integration

### LINKED ISSUE #44: CI server
We should add Travis support. It will allow us to briefly evaluate pull requests.

### PR DESCRIPTION
**Pull request by ForNeVeR**
It will close #44.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
cc @rexim as he is our general Travis specialist.

**Comment by rexim** [comment]
Please check your `.travis.yml` file with http://lint.travis-ci.org/

**Comment by ForNeVeR** [comment]
It keep saying "unexpected key scala", although it is explicitly mentioned [in the documentation](http://docs.travis-ci.com/user/languages/scala/). Does this fact have to change something? It validates successfully with this `scala` key removed.

**Comment by ForNeVeR** [comment]
I've checked and this "unexpected" key **does** affect the build: compare [#1](https://travis-ci.org/codingteam/Keter/builds/57235026) and [#3](https://travis-ci.org/codingteam/Keter/builds/57238122). So I'm putting it back.

**Comment by ForNeVeR** [comment]
So far it looks like everything is okay now. Or do you have something else in mind?

**Comment by rexim** [comment]
This is strange... Ok, I approve the request. :)

**Comment by ForNeVeR** [comment]
Okay, thanks!

**Pull request merged**
