### PR TITLE
Import documentation from Google Docs

### LINKED ISSUE #62: Migrate the game design documentation
(Spin-off from #59.)

We need to migrate the Google Docs to GitHub because of better version control and convenience.

### PR DESCRIPTION
**Pull request by ForNeVeR**
GitHub will be our official documentation storage.

Closes #62.

Currently blocked on #64.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
While we're waiting, I'd like to get someone's approval.

**Comment by rexim** [comment]
Hm... sorry wrong PR again :D

**Comment by hagane** [comment]
@ForNeVeR is there anything you want to complete before the merge? I'd like to start translating these docs after I get back home from a conf.

**Comment by ForNeVeR** [comment]
Nope, nothing. Feel free to branch this stuff and change it as you like; you may start right now. I'll deal with the merge outcome (e.g. rebase everything properly).

**Pull request closed without merging**
